# Generated by Django 4.1.1 on 2022-10-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='article_thumbnails/default.jpeg', upload_to='article_thumbnails/'),
        ),
    ]
